Selectable asyncio
puppylpg/oddish pull request #57
Opened 2020-12-14 17:37 UTC by zwwskm

# 要增加/修改的功能/修复的bug

由于每次爬取steam市场数据占用时间过多，且steam市场暂未观察到任何反爬/封号策略，故建议使用异步爬取。适当控制连接数量即可。

# 相关issue

# 改动内容描述

- 添加可选的异步爬取steam市场功能，默认最多同时5个链接，每次创建100个任务，出错一次时异步等待重试，出错两次时同步等待重试；
注：未测试异步请求下proxy参数的功能，不具备测试条件…

- 同步爬取steam市场时，减小等待间隔；

- 输出时加上了相对于成本的折扣数值，更直观。

还有十几天考研了，没法花时间写changelog，见谅…

# 核验信息
核验以下信息，已完成的项记得补全check box（中括号里填'x'）：
- [x] 是否测试过功能正确性；
- [] 是否修改CHANGELOG，增加变动描述；
- [] 确认是否需要修改README；
- [x] 新增代码是否有相应注释（或者代码是否清晰到足以不写注释）；

# 新代码效果截屏（建议）
![image](https://user-images.githubusercontent.com/51788980/102114637-575e0b00-3e32-11eb-8847-6cee9a12a525.png)

2020-12-15 03:02 UTC, puppylpg commented
好的，等我有时间了看一下，辛苦了～ 目前buff反爬比较严重，应对思路可能就是尽量减少buff api爬取、延长爬取buff api的时间间隔，同时尽量把api的访问转移到steam上，适当提高steam的访问速度（比如并发访问）。

非常及时的一个pull request，如果没时间后续我可以试着帮测一下，或者小修小改。

最后预祝考研顺利，心想事成～

2020-12-15 06:07 UTC, ccinv commented
没在python里写过异步 等我学完再看哈哈

另外 考研加油！

2020-12-15 06:52 UTC, puppylpg commented
> 没在python里写过异步 等我学完再看哈哈
> 
> 另外 考研加油！

好机会啊，看完这个，异步你就会了 :smiley_cat: :smiley_cat: :smiley_cat:

2020-12-15 08:09 UTC, zwwskm commented
哈哈哈，不瞒你们说，我也是对着文档现学现卖，零零散散改了一个星期才改好。网上异步的文档都质量参差不齐，好多都是过时的用法，最后对着英文文档才写出来的。

2020-12-15 08:45 UTC, puppylpg commented
哈哈哈，不瞒你们说，整个oddish我都是对着python api敲出来的 :sweat_smile: 怕不怕

2020-12-16 04:02 UTC, ccinv requested changes

2020-12-16 04:04 UTC, ccinv requested changes

2020-12-16 04:04 UTC, ccinv commented on src/util/requester.py
> +            async with session.get(url, proxies=proxies) as resp:
proxy的语法不是这样的，应该是
session.get(url, proxy=proxies["http"])

2020-12-16 08:32 UTC, zwwskm commented
修改了。顺手把一个warning也解决了，之前漏了个await。测试了proxy，应该没问题了。

2020-12-17 06:28 UTC, ccinv approved these changes

2020-12-17 06:28 UTC, ccinv commented on src/crawl/item_crawler.py
> +        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
觉得这个还是加在main里 而且写个平台判断比较好。
但先这样也没事

2020-12-21 00:33 UTC, ccinv commented on src/util/requester.py
>      if exist(url):
恩 是多余的

2020-12-21 01:08 UTC, zwwskm commented on src/util/requester.py
> +                return await resp.text()
这个……
await的话，我理解的就是text()是一种IO操作，是需要await的，参考官方文档里的示范代码
![image](https://user-images.githubusercontent.com/51788980/102729446-b0dda280-4328-11eb-88a1-71b1145dc935.png)
return的话，是因为只写await还没有return呀，需要return来传递回去的，不需要return的异步语法是早期的yield吧好像，已经不推荐使用了。

2020-12-21 01:12 UTC, zwwskm commented on src/util/requester.py
> +        timer.sleep_awhile()
这里是防止单个IP请求过多导致服务器暂时拒绝所有请求。如果还是异步休眠，那就别的协程还是一直在请求。出错一次我认为可能是网络原因或者怎么样导致第一次请求失败，连续出错两次就要考虑访问过快被拒绝的事情了，得全都休眠一下…我是这么想的
实际上我爬了几天了，还没遇到过这个全体休眠真正使用到的时候，steam服务器还是相当不错的嗷

2020-12-21 01:31 UTC, zwwskm commented on src/crawl/history_price_crawler.py
> +    # key existence check
这里问题是异步函数的定义是async def，没法直接在之前定义的同步函数里调用异步方法，所以所有的同步函数我都重新复制了一个出来…
如果把之前同步函数写成async def的话同步函数就没法用了，因为这种函数得用asyncio.run()调用否则报错，强行用了run()也会warning这个同步操作永远不会await；如果还用之前def的函数，只把里面的某个部分变成异步方法，那也是没法调用的，同步函数用不了run()方法。
但是其实可以把同步的操作（也就是get之后的判断、丢弃不符合的和输出日志）提取到新函数里，在异步和同步函数里都用上，这样能减少重复代码。我最近可能没时间优化这个了…要改就过几天吧。但是我感觉意义不大，把这个功能完整的函数拆成两部分还蛮费解的。

2020-12-21 03:49 UTC, puppylpg commented on src/crawl/history_price_crawler.py
> +    # key existence check
哦，你可能误解了我的意思。我明白所有的同步函数都要copy一份异步函数出来，我的意思是：

同步函数A包含abc三部分，a是同步等待的代码
异步函数A'包含a'bc三部分，a'是异步的代码

那么可以把bc抽成一个函数，A和A'都可以调用，就不用在二者里原封不动出现两次了

另外没时间优化的问题，不用着急，考研要紧，我们只是先把review意见放在这里，不急着merge回master，你先好好准备考研

加油加油↖(^ω^)↗↖(^ω^)↗↖(^ω^)↗

2021-01-09 18:02 UTC, merged